export {
  TableRoot,
  TableTitleBar,
  TableContextualBar,
  TableContextualAction,
  TableExpandCell,
  TableExpandedContentRow,
  TableScrollArea,
  TableElement,
  TableHead,
  TableBody,
  TableHeaderCell,
  TableBodyRow,
  TableBodyCell,
  TableFooterBar,
  TableSectionContext,
  TableColorsContext,
  TableRowSelectionContext,
  getTableCellPadding,
  getTableColors,
  useItamaratyTableSection,
  useTableSection,
  useTableRowSelected,
  DEFAULT_TABLE_SECTION,
  type TableRootProps,
  type TableTitleBarProps,
  type TableContextualBarProps,
  type TableContextualActionProps,
  type TableExpandCellProps,
  type TableExpandedContentRowProps,
  type TableScrollAreaProps,
  type TableElementProps,
  type TableSortDirection,
  type TableHeaderCellProps,
  type TableBodyRowProps,
  type TableBodyCellProps,
  type TableFooterBarProps,
  type TableDensity,
  type TableCellDividers,
  type DsTableColors,
  type TablePaddingSlot,
  type TableSectionState,
} from './Table'
export {
  TablePaginationBar,
  type TablePaginationBarProps,
  type TablePaginationBarLabels,
} from './TablePaginationBar'

/** Alias alinhado ao nome do componente no DS gov.br */
export { TableRoot as Table } from './Table'
